*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS BITCOMPILE BITHARDWARE BITCHANGE ldemulationarg CVF_LIBDIR USE_CLIB_DLL local_inst local_python_inst python_prefix python_win_prefix ctversion homedir ct_libdir ct_bindir ct_incdir ct_incroot ct_datadir ct_demodir ct_templdir ct_tutdir ct_docdir ct_dir ct_mandir COMPACT_INSTALL build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os username ctroot buildinc buildlib buildbin MAKE GRAPHVIZDIR ARCHIVE DO_RANLIB RANLIB USERDIR INCL_USER_CODE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT use_sundials CVODE_LIBS sundials_include CANTERA_DEBUG_MODE phase_object_files phase_header_files COMPILE_IDEAL_SOLUTIONS COMPILE_ELECTROLYTES NEED_CATHERMO WITH_REACTORS KERNEL KERNEL_OBJ BUILD_CK LIB_DIR build_lapack build_blas BLAS_LAPACK_LIBS BLAS_LAPACK_DIR build_with_f2c build_f2c_lib LOCAL_LIB_DIRS LOCAL_LIBS CT_SHARED_LIB PYTHON_CMD BUILD_PYTHON NUMARRAY_INC_DIR NUMARRAY_HOME CANTERA_PYTHON_HOME CVSTAG MATLAB_CMD BUILD_MATLAB BUILD_CLIB export_name INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CXX CXXFLAGS ac_ct_CXX CPP EGREP SOEXT SHARED PIC CXX_INCLUDES LCXX_FLAGS LCXX_END_LIBS HAVE_STRIPSYMBOLS F77 FFLAGS ac_ct_F77 FLIBS F90 BUILD_F90 F90FLAGS F90BUILDFLAGS precompile_headers CXX_DEPENDS OS_IS_DARWIN OS_IS_WIN OS_IS_CYGWIN SHARED_CTLIB mex_ext F77_EXT CXX_EXT OBJ_EXT EXE_EXT math_libs SO LDSHARED EXTRA_LINK TSCOMPARE_abs INSTALL_abs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS BITCOMPILE BITHARDWARE BITCHANGE ldemulationarg CVF_LIBDIR USE_CLIB_DLL local_inst local_python_inst python_prefix python_win_prefix ctversion homedir ct_libdir ct_bindir ct_incdir ct_incroot ct_datadir ct_demodir ct_templdir ct_tutdir ct_docdir ct_dir ct_mandir COMPACT_INSTALL build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os username ctroot buildinc buildlib buildbin MAKE GRAPHVIZDIR ARCHIVE DO_RANLIB RANLIB USERDIR INCL_USER_CODE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT use_sundials CVODE_LIBS IDA_LIBS sundials_include CANTERA_DEBUG_MODE phase_object_files phase_header_files COMPILE_IDEAL_SOLUTIONS COMPILE_ELECTROLYTES NEED_CATHERMO WITH_REACTORS KERNEL KERNEL_OBJ BUILD_CK LIB_DIR build_lapack build_blas BLAS_LAPACK_LIBS BLAS_LAPACK_DIR build_with_f2c build_f2c_lib LOCAL_LIB_DIRS LOCAL_LIBS CT_SHARED_LIB PYTHON_CMD BUILD_PYTHON NUMARRAY_INC_DIR NUMARRAY_HOME CANTERA_PYTHON_HOME CVSTAG MATLAB_CMD BUILD_MATLAB BUILD_CLIB export_name INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CXX CXXFLAGS ac_ct_CXX CPP EGREP SOEXT SHARED PIC CXX_INCLUDES LCXX_FLAGS LCXX_END_LIBS HAVE_STRIPSYMBOLS F77 FFLAGS ac_ct_F77 FLIBS F90 BUILD_F90 F90FLAGS F90BUILDFLAGS precompile_headers CXX_DEPENDS OS_IS_DARWIN OS_IS_WIN OS_IS_CYGWIN SHARED_CTLIB mex_ext F77_EXT CXX_EXT OBJ_EXT EXE_EXT math_libs SO LDSHARED EXTRA_LINK TSCOMPARE_abs INSTALL_abs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1323,10 +1323,24 @@ ac_config_sub="$SHELL $ac_aux_dir/config.sub"
 ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 
+if test -z $CANTERA_VERSION ; then
+  echo
+  echo ">>>>> Error <<<<<"
+  echo
+  echo "Run script 'preconfig', instead of running 'configure'"
+  echo "directly. The 'preconfig' script sets various variable values"
+  echo "needed by 'configure' and then runs 'configure.' You may want to"
+  echo "edit 'preconfig' first, to set various installation options."
+  echo
+  exit 1
+fi
+
+
 echo " "
 echo "--------------------------------------------------------------"
 echo " "
-echo "           Cantera Configuration Script "
+echo "           Cantera "$CANTERA_VERSION
+echo "         Configuration Script "
 echo " "
 echo "--------------------------------------------------------------"
 echo " "
@@ -1381,8 +1395,6 @@ if test $BITCOMPILE != $BITHARDWARE ; then
 fi
 
 
-# echo 'BITHARDWARE= ' $BITHARDWARE
-# echo 'BITCOMPILE= ' $BITCOMPILE
 
 
 
@@ -1394,7 +1406,7 @@ OS_IS_WIN=0
 OS_IS_CYGWIN=0
 EXTRA_LINK=${EXTRA_LINK:=""}
 
-
+# default Matlab MEX file extension
 mex_ext=mexglx
 
 case $ac_sys_system in
@@ -1410,7 +1422,6 @@ case $ac_sys_system in
             esac
 esac
 
-#echo "ldemulationarg = " $ldemulationarg
 
 
 
@@ -1708,6 +1719,7 @@ if test -n "$USER_SRC_DIR"; then USERDIR=$USER_SRC_DIR; INCL_USER_CODE=1; fi
 use_sundials=0
 sundials_inc=
 CVODE_LIBS='-lcvode'
+IDA_LIBS=''
 
 if test "$USE_SUNDIALS" = "default"; then
 ldsave=$LDFLAGS
@@ -2652,7 +2664,7 @@ if test "${ac_cv_lib_sundials_cvodes_CVodeCreate+set}" = set; then
 else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lsundials_cvodes \
--lsundials_shared -lsundials_nvecserial -lm $LIBS"
+-lsundials_cvodes -lsundials_nvecserial -lm $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2727,8 +2739,9 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 echo "using CVODES from SUNDIALS... Sensitivity analysis enabled."
-CVODE_LIBS='-lsundials_cvodes -lsundials_shared -lsundials_nvecserial'
-sundials_include='-I'${SUNDIALS_HOME}'/include -I'${SUNDIALS_HOME}'/include/sundials -I'${SUNDIALS_HOME}'/include/cvodes'
+CVODE_LIBS='-lsundials_cvodes -lsundials_nvecserial'
+IDA_LIBS='-lsundials_ida -lsundials_nvecserial'
+sundials_include='-I'${SUNDIALS_HOME}'/include -I'${SUNDIALS_HOME}'/include/sundials -I'${SUNDIALS_HOME}'/include/cvodes -I'${SUNDIALS_HOME}'/include/ida'
 echo "sundials include directory: " ${sundials_include}
 fi
 
@@ -2736,6 +2749,7 @@ if test ${use_sundials} = 0; then
 echo "using CVODE... Sensitivity analysis disabled."
 echo "-> To enable sensitivity analysis, install the SUNDIALS package with CVODES."
 fi
+
 
 
 
@@ -8537,7 +8551,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:8540:" \
+echo "$as_me:8554:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8740,7 +8754,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8743: \"$ac_link\") >&5
+(eval echo $as_me:8757: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8818,7 +8832,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8821: \"$ac_link\") >&5
+(eval echo $as_me:8835: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8992,9 +9006,9 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 override_f77_libs=0;
-#case $ac_sys_system in
-#  Darwin*)  FLIBS='-lSystem'; override_f77_libs=1; SHARED_CTLIB=0;;
-#esac
+case $ac_sys_system in
+  Darwin*)  FLIBS='-lSystem'; override_f77_libs=1; SHARED_CTLIB=0;;
+esac
 
 if test $override_f77_libs -gt 0; then
   echo The Fortran 77 libraries on this platform are not correctly determined by
@@ -9977,6 +9991,7 @@ s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@use_sundials@,$use_sundials,;t t
 s,@CVODE_LIBS@,$CVODE_LIBS,;t t
+s,@IDA_LIBS@,$IDA_LIBS,;t t
 s,@sundials_include@,$sundials_include,;t t
 s,@CANTERA_DEBUG_MODE@,$CANTERA_DEBUG_MODE,;t t
 s,@phase_object_files@,$phase_object_files,;t t
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -7,10 +7,24 @@ AC_CONFIG_HEADER(config.h)
 # AC_CONFIG_SRCDIR(./License.txt)
 AC_CONFIG_AUX_DIR(config)
 
+if test -z $CANTERA_VERSION ; then
+  echo 
+  echo ">>>>> Error <<<<<"
+  echo 
+  echo "Run script 'preconfig', instead of running 'configure'"
+  echo "directly. The 'preconfig' script sets various variable values"
+  echo "needed by 'configure' and then runs 'configure.' You may want to"
+  echo "edit 'preconfig' first, to set various installation options."
+  echo 
+  exit 1
+fi
+
+
 echo " "
 echo "--------------------------------------------------------------"
 echo " " 
-echo "           Cantera Configuration Script "
+echo "           Cantera "$CANTERA_VERSION
+echo "         Configuration Script "
 echo " " 
 echo "--------------------------------------------------------------"
 echo " "
@@ -62,8 +76,6 @@ if test $BITCOMPILE != $BITHARDWARE ; then
 fi
 
 
-# echo 'BITHARDWARE= ' $BITHARDWARE
-# echo 'BITCOMPILE= ' $BITCOMPILE
 AC_SUBST(BITCOMPILE)
 AC_SUBST(BITHARDWARE)
 AC_SUBST(BITCHANGE)
@@ -75,7 +87,7 @@ OS_IS_WIN=0
 OS_IS_CYGWIN=0
 EXTRA_LINK=${EXTRA_LINK:=""}
 
-
+# default Matlab MEX file extension
 mex_ext=mexglx
 
 case $ac_sys_system in
@@ -91,7 +103,6 @@ case $ac_sys_system in
             esac
 esac
 
-#echo "ldemulationarg = " $ldemulationarg
 AC_SUBST(ldemulationarg)
 
 
@@ -290,6 +301,7 @@ AC_SUBST(INCL_USER_CODE)
 use_sundials=0
 sundials_inc=
 CVODE_LIBS='-lcvode'
+IDA_LIBS=''
 
 if test "$USE_SUNDIALS" = "default"; then
 ldsave=$LDFLAGS
@@ -297,7 +309,7 @@ LDFLAGS='-L'$SUNDIALS_HOME/lib' '$ldsave
 fi
 
 AC_CHECK_LIB(sundials_cvodes, CVodeCreate, [use_sundials=1], [use_sundials=0],\
-[-lsundials_shared -lsundials_nvecserial -lm])
+[-lsundials_cvodes -lsundials_nvecserial -lm])
 
 if test "x$USE_SUNDIALS" = "xy"; then
 use_sundials=1
@@ -306,8 +318,9 @@ fi
 if test ${use_sundials} = 1; then
 AC_DEFINE(HAS_SUNDIALS)
 echo "using CVODES from SUNDIALS... Sensitivity analysis enabled."
-CVODE_LIBS='-lsundials_cvodes -lsundials_shared -lsundials_nvecserial' 
-sundials_include='-I'${SUNDIALS_HOME}'/include -I'${SUNDIALS_HOME}'/include/sundials -I'${SUNDIALS_HOME}'/include/cvodes'
+CVODE_LIBS='-lsundials_cvodes -lsundials_nvecserial' 
+IDA_LIBS='-lsundials_ida -lsundials_nvecserial' 
+sundials_include='-I'${SUNDIALS_HOME}'/include -I'${SUNDIALS_HOME}'/include/sundials -I'${SUNDIALS_HOME}'/include/cvodes -I'${SUNDIALS_HOME}'/include/ida'
 echo "sundials include directory: " ${sundials_include}
 fi
 
@@ -318,6 +331,7 @@ fi
 
 AC_SUBST(use_sundials)
 AC_SUBST(CVODE_LIBS)
+AC_SUBST(IDA_LIBS)
 AC_SUBST(sundials_include)
 
 
@@ -959,9 +973,9 @@ dnl Checks for libraries.
 AC_F77_LIBRARY_LDFLAGS()
 
 override_f77_libs=0;
-#case $ac_sys_system in
-#  Darwin*)  FLIBS='-lSystem'; override_f77_libs=1; SHARED_CTLIB=0;;
-#esac
+case $ac_sys_system in
+  Darwin*)  FLIBS='-lSystem'; override_f77_libs=1; SHARED_CTLIB=0;;
+esac
 
 if test $override_f77_libs -gt 0; then
   echo The Fortran 77 libraries on this platform are not correctly determined by 
